# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: packetlens.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'packetlens.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10packetlens.proto\x12\npacketlens\"H\n\rFeatureVector\x12\x0f\n\x07\x66low_id\x18\x01 \x01(\t\x12\x10\n\x08\x66\x65\x61tures\x18\x02 \x03(\x02\x12\x14\n\x0ctimestamp_ns\x18\x03 \x01(\x03\"X\n\x07Verdict\x12\x0f\n\x07\x66low_id\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x19\n\x11inference_time_us\x18\x04 \x01(\x03\x32R\n\x10InferenceService\x12>\n\x08\x43lassify\x12\x19.packetlens.FeatureVector\x1a\x13.packetlens.Verdict(\x01\x30\x01\x42\x31Z/github.com/mahmoud/packetlens/gen/go/packetlensb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'packetlens_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/mahmoud/packetlens/gen/go/packetlens'
  _globals['_FEATUREVECTOR']._serialized_start=32
  _globals['_FEATUREVECTOR']._serialized_end=104
  _globals['_VERDICT']._serialized_start=106
  _globals['_VERDICT']._serialized_end=194
  _globals['_INFERENCESERVICE']._serialized_start=196
  _globals['_INFERENCESERVICE']._serialized_end=278
# @@protoc_insertion_point(module_scope)
