# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import packetlens_pb2 as packetlens__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in packetlens_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub(object):
    """InferenceService provides real-time network intrusion detection.
    Uses bidirectional streaming for high-throughput, low-latency inference.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Classify = channel.stream_stream(
                '/packetlens.InferenceService/Classify',
                request_serializer=packetlens__pb2.FeatureVector.SerializeToString,
                response_deserializer=packetlens__pb2.Verdict.FromString,
                _registered_method=True)


class InferenceServiceServicer(object):
    """InferenceService provides real-time network intrusion detection.
    Uses bidirectional streaming for high-throughput, low-latency inference.
    """

    def Classify(self, request_iterator, context):
        """Classify opens a bidirectional stream where:
        - Client (Go Sniffer) sends FeatureVector messages
        - Server (Python) responds with Verdict messages
        This allows continuous inference without connection overhead.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Classify': grpc.stream_stream_rpc_method_handler(
                    servicer.Classify,
                    request_deserializer=packetlens__pb2.FeatureVector.FromString,
                    response_serializer=packetlens__pb2.Verdict.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'packetlens.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('packetlens.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """InferenceService provides real-time network intrusion detection.
    Uses bidirectional streaming for high-throughput, low-latency inference.
    """

    @staticmethod
    def Classify(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/packetlens.InferenceService/Classify',
            packetlens__pb2.FeatureVector.SerializeToString,
            packetlens__pb2.Verdict.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
